### PR TITLE
Issue 39

### PR DESCRIPTION
**Pull request by Abhishekm0410**
Added alternate text

### CODE REVIEW

**Comment by alokVerma749** [comment]
Hey, Great contribution👍, But there are too many changes in your PR, Please make a PR with the required changes only.

**Comment by Abhishekm0410** [comment]
I just pushed changes in one file still it is showing changes in 6 files. How can I solve this issue?

**Comment by alokVerma749** [comment]
just stage only required files, like `git add <fileName>`  instead of  `git add .`

**Comment by alokVerma749** [comment]
Hey Abhishek! 😊 I really appreciate your effort in contributing to the project, but I've noticed that the previous pull request didn't quite meet our requirements, making it difficult for me to merge it. Don't worry, though! I believe in your potential, and I know you can do better. How about crafting a new, fresh pull request with the necessary changes? I'm confident that with your skills, the new PR will be absolutely fantastic and irresistible! Let's work together to make it happen! 💪🚀

**Pull request closed without merging**
